### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by casimkhan** [ninoseki/eml_analyzer#13] opened 2020-07-01 03:07 UTC
I have tried different .eml and .msg but every time i see a Internal server error 
<img width="343" alt="Screen Shot 2020-07-01 at 1 05 51 pm" src="https://user-images.githubusercontent.com/17915197/86198820-d7055f80-bb9b-11ea-9e52-2021969090b0.png">

**Comment by ninoseki** [comment] 2020-07-01 03:38
Please attache the files when reporting. I have no clue to debug.

**Comment by casimkhan** [comment] 2020-07-01 04:27
which file you need ? copy of .eml?

**Comment by ninoseki** [comment] 2020-07-01 04:30
@casimkhan the files which raised errors.

**Comment by casimkhan** [comment] 2020-07-02 02:04
here is one sample file .. i tried running docker image and it didnt work as well 
[Cybersecurity_Summit Agenda.zip](https://github.com/ninoseki/eml_analyzer/files/4861568/Cybersecurity_Summit.Agenda.zip)

**Comment by ninoseki** [comment] 2020-07-02 04:33
@casimkhan 
This Received header looks strange to me.

```
Received: from xyz.com (10.0.0.1) by xyz.com
 (10.32.136.239) with Microsoft SMTP Server id 14.3.408.0; Wed, 17 Jul 2019
 05:01:28 +1000
```

Is this a manipulated EML file?  Or an original EML file?

**Comment by casimkhan** [comment] 2020-07-02 04:44
yup its redacted

**Comment by ninoseki** [comment] 2020-07-02 04:46
@casimkhan please share the original file to debug correctly.

**Comment by casimkhan** [comment] 2020-07-03 02:00
thats why i have done .. i have just redacted ip address and domains from SMTP headers

**Comment by ninoseki** [comment] 2020-07-03 05:01
I will close this issue if you cannot provide the EML file which raises the error because your issue is not reproducible for me.
You can share the file with me by using PGP.
https://flowcrypt.com/pub/manabu.niseki@gmail.com

**Comment by ninoseki** [comment] 2020-07-07 01:28
Close this issue because there is no response from @casimkhan.
(I will reopen the issue if you submit the EML sample)

**Closed by ninoseki** 2020-07-07 01:28 UTC

**Comment by casimkhan** [comment] 2020-07-07 05:23
just checked again .. and its working. Thanks
